# Generated by Django 4.2.27 on 2026-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-create_time'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='分类名称'),
        ),
    ]
