# Generated by Django 4.2.27 on 2026-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_logistics_info_and_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '待发货'), (3, '已发货'), (4, '已完成'), (5, '已取消')], default=0, verbose_name='订单流转状态'),
        ),
    ]
