# Generated by Django 4.2.27 on 2026-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='取消原因'),
        ),
    ]
