# Generated by Django 4.2.27 on 2026-01-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_goods_stock_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学校'),
        ),
    ]
