from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('publish/', views.goods_publish, name='goods_publish'),
    path('goods/', views.goods_list, name='goods_list'),
    path('goods/<int:goods_id>/', views.goods_detail, name='goods_detail'),
    path('order/create/<int:goods_id>/', views.order_create, name='order_create'),
    path('api/addresses/', views.api_addresses, name='api_addresses'),
    path('api/order/create/', views.api_order_create, name='api_order_create'),
    path('order/list/', views.order_list, name='order_list'),
    path('order/deliver/<int:order_id>/', views.mark_order_delivered, name='mark_order_delivered'),
    path('order/confirm/<int:order_id>/', views.confirm_order_received, name='confirm_order_received'),
    path('order/<int:order_id>/aftersale/apply/', views.apply_after_sale, name='apply_after_sale'),
    path('order/<int:order_id>/aftersale/handle/', views.handle_after_sale, name='handle_after_sale'),
    path('order/<int:order_id>/aftersale/complete/', views.complete_after_sale, name='complete_after_sale'),
    path('order/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('order/<int:order_id>/cancel/ajax/', views.cancel_order_ajax, name='cancel_order_ajax'),
    path('order/<int:order_id>/seller-cancel/', views.seller_cancel_order_ajax, name='seller_cancel_order'),
    path('order/<int:order_id>/delete/', views.delete_order_ajax, name='delete_order'),
    path('order_pay/', views.order_pay, name='order_pay'),
    path('personal/goods/', views.my_goods, name='my_goods'),
    path('favorite/toggle/<int:goods_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('favorite/list/', views.favorite_list, name='favorite_list'),
    path('reports/my/', views.my_reports, name='my_reports'),
    path('goods/<int:goods_id>/delist/', views.delist_goods, name='delist_goods'),
    path('goods/<int:goods_id>/edit/', views.goods_edit, name='goods_edit'),
    path('goods/<int:goods_id>/report/', views.add_goods_report, name='add_goods_report'),
    path('order/<int:order_id>/deliver/fragment/', views.deliver_fragment, name='deliver_fragment'),
    path('comment/add/', views.add_comment, name='add_comment'),
    path('comment/goods/<int:goods_id>/', views.get_goods_comments, name='get_goods_comments'),
    path('comment/my/', views.my_comments, name='my_comments'),
    path('profile/', views.profile, name='profile'),
    path('personal/address/', views.manage_address, name='manage_address'),
    path('personal/address/<int:addr_id>/detail/', views.address_detail, name='address_detail'),
    path('personal/address/add/', views.add_address, name='add_address'),
    path('personal/address/fragment/<int:addr_id>/', views.address_fragment, name='address_fragment'),
    path('personal/address/edit/<int:addr_id>/', views.edit_address, name='edit_address'),
    path('personal/address/delete/<int:addr_id>/', views.delete_address, name='delete_address'),
    path('personal/address/set_default/<int:addr_id>/', views.set_default_address, name='set_default_address'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('personal/center/', views.personal_center, name='personal_center'),
    path('personal/avatar/update/', views.update_avatar, name='update_avatar'),
    path('personal/profile/update/', views.update_profile, name='update_profile'),
    path('personal/password/update/', views.update_password, name='update_password'),
]
